routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::resource('questions','QuestionController')->except('show');
Route::get('/questions/{slug}','QuestionController@show')->name('questions.show');

app/Answer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    public function question(){
      return  $this->belongsTo(Question::class);
    }


    public function user(){
        return $this->belongsTo(User::class);
    }

    public function getCreatedDateAttribute(){
        return $this->created_at->diffforHumans();
    }


    public static function boot(){
        parent::boot();

        static::created(function($answer){
            $answer->question->increment('answers_count');
            $answer->question->save();
        });
    }
}

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Parsedown;
class Question extends Model
{

    protected $fillable = ['title','body'];
    public function user(){
        return $this->belongsTo(User::class);
    }

    public function setTitleAttribute($value){
        $this->attributes['title'] = $value;
        $this->attributes['slug'] = Str::slug($value);
    }

    public function getUrlAttribute(){
        return route("questions.show", $this->slug);
    }


    public function getCreateDateAttribute(){
        return $this->created_at->diffforHumans();
    }

    public function getStatusAttribute(){
        if($this->best_ansewer_id){

            return "answered-accepted";
        }

        if($this->answers_count>0){
            return "answered";
        }
        return "unanswered";
    }


    public function getBodyHtmlAttribute(){
        return \Parsedown::instance()->text($this->body);
    }

    public function answers(){
      return $this->hasMany(Answer::class);
    }


}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function questions(){
        return $this->hasMany(Question::class);
    }


    public function getUrlAttribute(){
        return "#";
    }

    public function getAvatarAttribute(){
        $email = $this->email;
        $size = 32;
        return "https://www.gravatar.com/avatar/" . md5( strtolower( trim( $email ) ) ) . "&s=" . $size;
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use Illuminate\Http\Request;
use App\Http\Requests\AskQuestionRequest;
class QuestionController extends Controller
{

    public function __construct(){
        $this->middleware('auth',['except'=>['index','show']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $questions = Question::latest()->paginate(5);
       return view('questions.index',compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
     $question = new Question();
      return view('questions.create',compact('question'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AskQuestionRequest $request)
    {
            $request->user()->questions()->create($request->only('title','body'));

            return redirect()->route('questions.index')->with('success','Your questions has been submited');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        $question->increment('views');
        return view('questions.show',compact('question'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        $this->authorize("update",$question);

        if(\Gate::denies('update-question',$question)){
           abort(403, "Accès refusé");
        }
        return view('questions.edit',compact('question'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(AskQuestionRequest $request, Question $question)
    {
        $this->authorize("update",$question);

        if(\Gate::denies('update-question',$question)){
            abort(403, "Accès refusé");
         }
        $question->update($request->only('title','body'));
        return redirect()->route('questions.index')->with('warning','Your question has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        $this->authorize("delete",$question);

        if(\Gate::denies('delete-question',$question){
            abort(403, "Accès refusé.")
        });
        $question->delete();
        return redirect()->route('questions.index')->with('danger','Your question has been deleted!');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/_messages.blade.php
@if(session('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
   <strong>Success! </strong>{{ session('success') }}
   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
@endif
@if (session('warning'))
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Updated! </strong>{{ session('warning') }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
     <span aria-hidden="true">&times;</span>
   </button>
 </div>
 @endif
 @if(session('danger'))
 <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Deleted! </strong>{{ session('danger') }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
     <span aria-hidden="true">&times;</span>
   </button>
 </div>
@endif

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/questions/_form.blade.php
@csrf
<div class="form-group">
    <label for="question-title">
        Question Title
    </label>
    <input type="text" name="title" value="{{old('title', $question->title)}}" id="question-title" class="form-control {{$errors->has('title') ? 'is-invalid':''}}">
    @if($errors->has('title'))
    <div class="invalid-feedback">
        <strong>{{$errors->first('title')}}</strong>
    </div>
    @endif
</div>

<div class="form-group">
    <label for="question-bady">
        Explain your question
    </label>
   <textarea name="body" id="question-body" rows="5" class="form-control {{$errors->has('body') ? 'is-invalid':''}}">{{old('body',$question->body)}}</textarea>
   @if($errors->has('bady'))
    <div class="invalid-feedback">
        <strong>{{$errors->first('body')}}</strong>
    </div>
    @endif
</div>

<div class="form-group">
    <button type="submit" class="btn btn-outline-primary btn-lg">{{$buttonText}}</button>
</div>

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h2>Back to all Questions</h2>
                        <div class="ml-auto">
                            <a href="{{route('questions.index')}}" class="btn btn-outline-secondary btn-small">Back to all questions</a>
                        </div>
                    </div>
                    </div>

                <div class="card-body">
                    <form action="{{route('questions.store')}}" method="post">
                       @include('questions._form',['buttonText'=>'Ask question'])
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h2>Back to all Questions</h2>
                        <div class="ml-auto">
                            <a href="{{route('questions.index')}}" class="btn btn-outline-secondary btn-small">Back to all questions</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{route('questions.update',$question->id)}}" method="post">
                        @csrf
                        @method('put')
                       @include('questions._form',['buttonText'=>'Update question'])
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h2>All Questions</h2>
                        <div class="ml-auto">
                            <a href="{{route('questions.create')}}" class="btn btn-outline-secondary btn-small">Add Question</a>
                        </div>
                    </div>
                    </div>

                <div class="card-body">
                        @include('layouts._messages')

                   @foreach ($questions as $question)
                        <div class="media">
                            <div class="d-flex flex-column counters">
                                <div class="vote">
                                    <strong>{{$question->votes}}</strong>
                                    {{ Str::plural('vote',$question->votes) }}
                                </div>

                                <div class="status {{$question->status}}">
                                    <strong>{{$question->answers_count}}</strong>
                                    {{ Str::plural('answer',$question->answers_count) }}
                                </div>

                                <div class="view">
                                    {{$question->views." ". Str::plural('view',$question->view) }}
                                </div>
                            </div>
                            <div class="media-body">
                                <div class="d-flex align-items-center">
                                   <h3 class="mt-0"> <a href="{{$question->url}} "> {{ $question->title}}</a></h3>

                                   <div class="ml-auto">
                                    @can('update',$question)
                                        <a href="{{route('questions.edit',$question->id)}}" class="btn btn-sm btn-outline-info">Edit</a>
                                    @endcan
                                    @can('delete',$question)
                                        <form class="form-delete" action="{{route('questions.destroy', $question->id)}}" method="post">
                                            @method('delete')
                                            @csrf
                                            <button type="submit" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are you Sure?')">Delete</button>
                                        </form>
                                    @endcan
                                    </div>

                                </div>
                                <h3 class="mt-0">
                                    <p class="lead">
                                         Asked by <a href="{{$question->user->url}}">{{$question->user->name}}</a>
                                       <small class="text-muted">
                                       {{ $question->created_at}}
                                       </small>
                                    </p>
                                </h3>
                                <p> {{ Str::limit($question->body,250,'...') }}</p>
                            </div>

                        </div>
                        <hr>
                   @endforeach
                  <div class="text-center">
                    {{ $questions->links() }}
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="card-title">
                        <div class="card-title">
                            <div class="d-flex align-items-center">
                                <h1>{{$question->title}}</h1>
                                <div class="ml-auto">
                                    <a href="{{route('questions.index')}}" class="btn btn-outline-secondary btn-small">Back to all questions</a>
                                </div>
                            </div>
                            </div>
                            <hr>
                        <div class="media">
                            <div class="d-flex-column vote-controls">
                                <a href="" title="This question is useful" class="vote-up">
                                    <i class="fas fa-caret-up fa-3x"></i>
                                </a>
                                <span class="votes-count">232</span>
                                <a href="" title="This question is not useful" class="vote-down off"> <i class="fas fa-caret-down fa-3x"></i></a>
                                <a href="" title="click to mart  fovarite question (click again to undo)" class="favorite favorited"><i class="fas fa-star fa-3x"></i>
                                </a>
                                <span class="favorites-count"></span>
                            </div>
                            <div class="media-body">
                                {{ $question->body}}
                            <div class="float-right">
                                <span class="text-muted">
                                    Asked by {{ $question->created_date }}
                                </span>
                                <a href="{{$question->user->url}}" class="pr-2">
                                    <img src="{{$question->user->avatar}}" alt="" srcset="">
                                </a>
                                <div class="media-body">
                                    <a href="{{$question->user->url}}">
                                        {{ $question->user->name }}
                                    </a>
                                </div>
                            </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-bady">
                    <div class="card-title">
                        <h2>
                            {{ $question->answers_count. " ". Str::plural('Answer',$question->answers_count)}}
                        </h2>
                        <hr>
                        @foreach ($question->answers as $answer)
                            <div class="media">
                              <div class="d-flex-column vote-controls">
                                        <a href="" title="This question is useful" class="vote-up">
                                            <i class="fas fa-caret-up fa-3x"></i>
                                        </a>
                                        <span class="votes-count">232</span>
                                        <a href="" title="This question is not useful" class="vote-down off"> <i class="fas fa-caret-down fa-3x"></i></a>
                                        <a href="" title="click to mart  fovarite question" class="favorite "><i class="fas fa-check fa-3x"></i>
                                        </a>
                            </div>
                                <div class="media-body">
                                    {{ $answer->body }}
                                    <div class="float-right">
                                        <span class="text-muted">
                                            Answered {{ $answer->created_date }}
                                        </span>
                                        <a href="{{$answer->user->url}}" class="pr-2">
                                            <img src="{{$answer->user->avatar}}" alt="" srcset="">
                                        </a>
                                        <div class="media-body">
                                            <a href="{{$answer->user->url}}">
                                                {{ $answer->user->name }}
                                            </a>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


@endsection